services = ["Additions Remodeling", "Air Conditioning", 
    "Appliances", 
    "Appraiser", 
    "Architects Engineers", 
    "Art Mirror Mounting", 
    "Audio/Visual Computers", 
    "Awnings", "Brick Stone", 
    "Cabinets", "Carpenters", 
    "Carpet Upholstery Cleaning", 
    "Ceilings", "Central Vacuum", 
    "Cleaning Maid Services", 
    "Concrete", 
    "Countertops", 
    "Decks", 
    "Demolition Service", 
    "Designers Decorators", 
    "Developer", 
    "Disability Services", 
    "Disaster Recovery Services", 
    "Docks", 
    "Doors", 
    "Drywall Plaster", 
    "Electrical", 
    "Excavation", 
    "Fans", 
    "Fences", 
    "Fireplace Wood Stoves", 
    "Fitness Sports Equipment Assembly", 
    "Flooring Carpet", 
    "Foundations", 
    "Fountains Ponds", 
    "Furniture Assembly", 
    "Furniture Repair Refinish", 
    "Garage Garage Doors", 
    "Glass Mirrors", 
    "Gutters", 
    "Handyman Services",
    "Heating Furnace Systems",
    "Home Inspection",
    "Home Maintenance",
    "Home Security Services",
    "Hot Tubs, Spas Saunas",
    "Household Help",
    "Insulation",
    "Landscaping",
    "Lawn Garden Care",
    "Lifting Moving Heavy Items",
    "Locksmith",
    "Metal Fabrication",
    "Mold Asbestos Services",
    "Moving",
    "New Home Builders",
    "Organizers",
    "Outdoor Playgrounds",
    "Packing Unpacking Services",
    "Painting",
    "Paving",
    "Permit Services",
    "Pest Control",
    "Plumbing",
    "Powdercoating",
    "Power Washing",
    "Roofing",
    "Sandblasting Service",
    "Septic Tanks Wells",
    "Sheds Enclosures",
    "Siding",
    "Sign Making Service",
    "Skylights",
    "Snow Removal Service",
    "Solar",
    "Stained Glass",
    "Swimming Pools",
    "Tennis or Game Court",
    "Tile",
    "Tree Service",
    "Wall Coverings",
    "Waste Material Removal",
    "Water Treatment System",
    "Waterproofing",
    "Window Coverings",
    "Windows",
    "Yard Garden Work"]

formattedServices = []

for service in services:
    real = ""
    for char in service:
        if char == " " or char == "/":
            real += "-"
        else:
            real += char
    formattedServices.append(real)